src/auth_app/urls.py
from django.urls import path
from . import views

app_name= "auth_app"

urlpatterns = [
    path("register",views.register_view, name="register"),
    path("", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

src/chantier_app/urls.py
from django.urls import path
from . import views

app_name = 'chantier_app'

urlpatterns = [
    
    #URLs pour la gestion des chantiers
    path("chantier/", views.ChantierListeView.as_view(), name="liste-chantier"),
    path("ajouter-chantier/", views.ChantierCreateView.as_view(), name="ajouter-chantier"),
    path("<int:pk>/detail-chantier/", views.ChantierDetailView.as_view(), name="detail-chantier"),
    path("<int:pk>/modifier-chantier/", views.ChantierUpdateView.as_view(), name="modifier-chantier"),
    path("<int:pk>/supprimer-chantier/", views.ChantierDeleteView.as_view(), name="supprimer-chantier"),
    
    
#URL pour le filtrage HTMX des chantiers    
    path('filter-chantiers', views.filter_chantiers_htmx, name="filter-chantiers"),
    
]

src/client_app/urls.py
from django.urls import path
from . import views

app_name = 'client_app'

urlpatterns = [
#URLs pour la gestion des clients
    path("client/", views.ClientListView.as_view(), name="liste-client"),
    path("ajouter-client/", views.ClientCreateView.as_view(), name="ajouter-client"),
    path("<int:pk>/", views.ClientDetailView.as_view(), name="detail-client"),
    path("<int:pk>/modifier-client/", views.ClientUpdateView.as_view(), name="modifier-client"),
    path("<int:pk>/supprimer-client/", views.ClientDeleteView.as_view(), name="supprimer-client"),
         ]

src/comptable_app/urls.py
from django.urls import path
from . import views

app_name="comptable_app"

urlpatterns = [
    
    path("interface-comptable",views.comptable_view, name='comptable-view'),
    path("comptable-approuver/<int:demande_id>/demande", views.comptable_approuve_demande_view, name="comptable-approuver-demande"),
    path("comptable-refuser/<int:demande_id>/demande", views.comptable_refuse_demande_view, name="comptable-refuser-demande"),
    path("comptable-ajouter-fond", views.ajouter_fond, name="comptable-ajouter-fond"),
    path("comptable-rapport-depense-employee", views.list_rapport_depense_view, name="comptable-rapport-depense-employee")
]

src/directeur_app/urls.py
from django.urls import path
from . import views

app_name ="directeur_app"

urlpatterns = [
    path("interface-directeur",views.directeur_view, name='directeur-view'),
    path("approuver/<int:demande_id>/demande", views.approuve_demande_view, name="approuver-demande"),
    path("refuser/<int:demande_id>/demande", views.refuse_demande_view, name="refuser-demande"),
    path("ajouter-fond", views.ajouter_fond, name="ajouter-fond"),
    path("rapport-depense-employee", views.list_rapport_depense_view, name="rapport-depense-employee")
]

src/sanba_finflow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("auth_app.urls")),
    path("", include("directeur_app.urls")),
    path("", include("secretaire_app.urls")),
    path("", include("employee_app.urls")),
    path("", include("comptable_app.urls")),
    path("", include("client_app.urls")),
    path("", include("chantier_app.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/directeur_templates/directeur.html
{% extends 'base.html' %}



{% block title %}
    Interface Directeur
{% endblock title %}



{% block content %}

<!-- EN HAUT du template -->
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}


<h2>Fond disponible: {{ fond }}</h2>
<a href="{% url 'auth_app:register' %}">Ajouter un employée</a>
<a href="{% url 'directeur_app:ajouter-fond' %}">Ajouter des fonds</a>
<a href="{% url 'directeur_app:rapport-depense-employee' %}">Rapport des dépenses </a>

<a href="{% url 'client_app:liste-client' %}">Liste des clients</a>

<a href="{% url 'chantier_app:liste-chantier' %}">Voir tout les chantier</a>



<a href="{% url 'auth_app:logout' %}">Deconnexion</a>
<div class='list_demande'>
    <hr>
    <hr>
    <h1>Interface Directeur</h1>
<h1>List et status de demande en cours</h1>

{% for demande in list_demande %}
    <h3>{{ demande.nom  }}</h3>
    <h4><em>{{ demande.montant }}</em></h4>
    <h4>{{ demande.chantier}}</h4>
    <p>{{ demande.motif }}</p>
    
   
 {% if demande.status == 'approuvee_directeur' or demande.status == 'approuvee_comptable' %}
   <h3 style='color:green;'>{{ demande.status }}</h3>
   {% elif demande.status == 'decaisse' %}
    <h3 style='color:skyblue;'>{{ demande.status }}</h3>

   {% elif demande.status == 'refusee_directeur' or demande.status == 'refusee_comptable' %}
    <h3 style='color:red;'>{{ demande.status }}</h3>
    {% else %}
    <h3 style='color:orange;'>{{ demande.status }}</h3>

      <a href="{% url 'comptable_app:comptable-approuver-demande' demande.id %}" style='color: green;'>Approuver</a>
         <a href="{% url 'comptable_app:comptable-refuser-demande' demande.id %}"style='color: red;'>Refusé</a>
   {% endif %}
    
        
    
    <hr>
    <hr>
{% endfor %}
    
</div>
{% endblock content %}
    

src/templates/directeur_templates/rapport_employee.html
{% extends 'base.html' %}


{% block title %}
    Rapport des dépense
{% endblock title %}




{% block content %}

<!-- EN HAUT du template -->
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
<h1>Rapport des dépenses des employés</h1>
    <table>
        <thead>
            <tr>Nom</tr>
            <tr>Type depense</tr>
            <tr>Matériaux/Articles</tr>
            <tr>Prix unitaire</tr>
            <tr>Chantier</tr>
            <tr>Quantité</tr>
            <tr>Fournisseur</tr>
            <tr>Facture</tr>
        </thead>
         {% for rapport_depense in list_rapport_depense  %}
   
        <tbody>

            <td>{{rapport_depense.employee}}</td>
            <td>{{rapport_depense.type_depense}}</td>
            <td>{{rapport_depense.materiau_article}}</td>
            <td>{{rapport_depense.prix_unitaire}}</td>
            <td>{{rapport_depense.chantier}}</td>
            <td>{{rapport_depense.quantité}}</td>
            <td>{{rapport_depense.fournisseur}}</td>
            <td>{{rapport_depense.fature}}</td>

   
        </tbody>
        {% endfor %}
         </table>
       
        
        
{% endblock content %}
    
    