src/auth_app/urls.py
from django.urls import path
from . import views

app_name= "auth_app"

urlpatterns = [
    path("register",views.register_view, name="register"),
    path("", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

src/chantier_app/urls.py
from django.urls import path
from . import views

app_name = 'chantier_app'

urlpatterns = [
    
    #URLs pour la gestion des chantiers
    path("chantier/", views.ChantierListeView.as_view(), name="liste-chantier"),
    path("ajouter-chantier/", views.ChantierCreateView.as_view(), name="ajouter-chantier"),
    path("<int:pk>/detail-chantier/", views.ChantierDetailView.as_view(), name="detail-chantier"),
    path("<int:pk>/modifier-chantier/", views.ChantierUpdateView.as_view(), name="modifier-chantier"),
    path("<int:pk>/supprimer-chantier/", views.ChantierDeleteView.as_view(), name="supprimer-chantier"),
    
    
#URL pour le filtrage HTMX des chantiers    
    path('filter-chantiers', views.filter_chantiers_htmx, name="filter-chantiers"),
    
]

src/client_app/urls.py
from django.urls import path
from . import views

app_name = 'client_app'

urlpatterns = [
#URLs pour la gestion des clients
    path("client/", views.ClientListView.as_view(), name="liste-client"),
    path("ajouter-client/", views.ClientCreateView.as_view(), name="ajouter-client"),
    path("<int:pk>/", views.ClientDetailView.as_view(), name="detail-client"),
    path("<int:pk>/modifier-client/", views.ClientUpdateView.as_view(), name="modifier-client"),
    path("<int:pk>/supprimer-client/", views.ClientDeleteView.as_view(), name="supprimer-client"),
         ]

src/sanba_finflow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("auth_app.urls")),
    path("", include("directeur_app.urls")),
    path("", include("secretaire_app.urls")),
    path("", include("employee_app.urls")),
    path("", include("comptable_app.urls")),
    path("", include("client_app.urls")),
    path("", include("chantier_app.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/chantiers_templates/chantiers_liste.html
{% extends 'base.html' %}


{% block title %}
Chantiers
{% endblock title %}
    

{% block content %}

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}


<h1>Liste des Chantiers</h1>
<a href="{% url 'chantier_app:ajouter-chantier' %}">Ajouter nouveau Chantier</a>

{% for chantier in chantiers %}
    <p>Nom du chantier : {{ chantier.nom_chantier }} </p>- 
    <p> Client: <a href="{% url 'client_app:detail-client' chantier.client.id %}">{{ chantier.client.nom }} {{ chantier.client.prenom }}</a></p>
    <p> Status actuelle : {{ chantier.status_chantier }}</p>
    <p>Reference: {{chantier.reference}}</p>
    
    
{% endfor %}
    

{% endblock content %}
    

src/templates/chantiers_templates/details_chantier.html
{% extends 'base.html' %}

{% block title %}
    Détails du Chantier
{% endblock title %}

{% block content %}
<h1>Détails du Chantier: {{ chantier.nom_chantier }}</h1>
<p>Référence: {{ chantier.reference }}</p>
<p>Client: <a href="{% url 'client_app:detail-client' chantier.client.id %}">{{ chantier.client.nom }} {{ chantier.client.prenom }}</a></p>
<p>Status: {{ chantier.status_chantier }}</p>
<p>Adresse: {{ chantier.adresse_chantier }}, {{ chantier.quartier_chantier }}, {{ chantier.ville_chantier }}, {{ chantier.pays_chantier }}</p>
<p>GPS: Latitude {{ chantier.gps_latitude }}, Longitude {{ chantier.gps_longitude }}</p>
<p>Date de début prévue: {{ chantier.date_debut_prevue }}</p>
<p>Date de fin prévue: {{ chantier.date_fin_prevue }}</p>
<p>Date de début réelle: {{ chantier.date_debut_reelle }}</p>
<p>Date de fin réelle: {{ chantier.date_fin_reelle }}</p>

   <p>Équipe affectée: 
    {% for membre in chantier.equipe_affectee.all %}
        <span class="badge">{{ membre.username }} </span>
    {% empty %}
        <span class="text-muted">Aucune équipe affectée</span>
    {% endfor %}
</p>
    <p>Budget: {{ chantier.budget_total }}</p>

    <a href="{% url 'chantier_app:modifier-chantier' chantier.id %}">Modifier le chantier</a>
    <a href="{% url 'chantier_app:supprimer-chantier' chantier.id %}">Supprimer le chantier</a>
</p>
{% endblock content %}