src/auth_app/urls.py
from django.urls import path
from . import views

app_name= "auth_app"

urlpatterns = [
    path("register",views.register_view, name="register"),
    path("", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

src/sanba_finflow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("auth_app.urls")),
    path("", include("directeur_app.urls")),
    path("", include("secretaire_app.urls")),
    path("", include("employee_app.urls")),
    path("", include("comptable_app.urls")),
    path("", include("client_app.urls")),
    path("", include("chantier_app.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/secretaire_app/urls.py
from django.urls import path
from . import views

app_name = "secretaire_app"

urlpatterns = [
    path("interface-secretaire", views.demande_decaissement_view, name="secretaire-view"),
    path("valider-decaissement/<int:decaissement_id>", views.valider_decaissement_view, name="valider-decaissement")
]

src/templates/secretaire_templates/secretaire.html
{% extends 'base.html' %}


{% block title %}
    interface secretaire
{% endblock title %}

<!-- EN HAUT du template -->
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}


{% block content %}



<h2>Fond disponible: {{ fond }}</h2>

<a href="{% url 'auth_app:logout' %}">Deconnexion</a>
<div class='demande_decaisse'>

<h1>Soumettre demande de décaissement</h1>

    <form action="{% url 'secretaire_app:secretaire-view'%}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Soumettre demande de decaissement">
    </form>

</div>

<div class='list_demande'>
  
    
    <h1>List et status de demande en cours</h1>
    <hr>
    <hr>
    {% for demande in list_demande %}
        <h3>{{ demande.nom  }}</h3>
        <h4><em>{{ demande.montant }}</em></h4>
        <h4>{{ demande.chantier}}</h4>
        <p>{{ demande.motif }}</p>

        <div class='status'>
        {% if demande.status == 'approuvee_directeur' or demande.status == 'approuvee_comptable'  %}
       <h3 style='color:green;'>{{ demande.status }}</h3>

       <a href="{% url 'secretaire_app:valider-decaissement' demande.id %}">Validez déccaissement</a>
        {% elif demande.status == 'decaisse' %}
        <h3 style='color:skyblue;'>{{ demande.status }}</h3>

       {% elif demande.status == 'refusee_directeur' or demande.status == 'refusee_comptable' %}
        <h3 style='color:red;'>{{ demande.status }}</h3>
        {% else %}
        <h3 style='color:orange;'>{{ demande.status }}</h3>
       {% endif %}
        </div>
        
        <hr>
        <hr>
    {% endfor %}
    
</div>
    
{% endblock content %}
    
    